apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS taskmanagerdb;
    USE taskmanagerdb;

    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL UNIQUE
    );

    CREATE TABLE IF NOT EXISTS tasks (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(255),
      completed BOOLEAN DEFAULT false,
      user_id INT NOT NULL,
      INDEX (user_id),
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );