apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: back-binding
  namespace: task-manager
subjects:
  - kind: ServiceAccount
    name: back-sa
    namespace: task-manager
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: back-user-binding
  namespace: task-manager
subjects:
  - kind: ServiceAccount
    name: back-user-sa
    namespace: task-manager
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: front-binding
  namespace: task-manager
subjects:
  - kind: ServiceAccount
    name: front-sa
    namespace: task-manager
roleRef:
  kind: Role
  name: viewer-role
  apiGroup: rbac.authorization.k8s.io