apiVersion: v1
kind: ServiceAccount
metadata:
  name: back-sa
  namespace: task-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: back-user-sa
  namespace: task-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: front-sa
  namespace: task-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: task-manager